In [1]:
x = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
y = [1, 3, 2, 5, 7, 8, 8, 9, 10, 12]
n=10

In [2]:
import numpy as np
import pandas as pd
y=np.array(y)
x=np.array(x)

In [4]:
x_s=np.sum(x)
y_s=np.sum(y)
x_2_s=np.sum(x**2)
x_y_s=np.sum(x*y)

In [5]:
print("Σx=", x_s)
print("Σx^2=", x_2_s)
print("Σy=", y_s)
print("Σxy=",x_y_s)

Σx= 45
Σx^2= 285
Σy= 65
Σxy= 389


In [6]:
A=np.array([[n,x_s],[x_s,x_2_s]])

In [7]:
print(A)

[[ 10  45]
 [ 45 285]]


In [8]:
B=np.array([[y_s],[x_y_s]])

In [9]:
print(B)

[[ 65]
 [389]]


In [24]:
#AX=B
#X=A^-1xB
A_inv = np.linalg.inv(A)
#X=np.round(np.dot(A_inv,B),2).astype(float)
X=np.dot(A_inv,B)
print(X)

[[1.23636364]
 [1.16969697]]


In [40]:
print(np.dot(A,X))
print(X.shape)

[[ 65.]
 [389.]]
(2, 1)


In [47]:
def  y_com(x):
    return (1.16969697*(x)+1.23636364)

In [48]:
sse=0
for i in range(n):
    sse=sse+((y[i]-y_com(x[i]))**2)
print("SSE=",sse)    

SSE= 5.624242424242421


In [49]:
y_m=(y_s)/10
print("y_mean =",y_m)
ssr=0
for i in range(n):
    ssr=ssr+((y_com(x[i]-y_m)**2))
print(ssr)    

y_mean = 6.5
125.04251606142331


In [50]:
sst=ssr+sse
R_2=ssr/sst
print("R_2=",R_2)

R_2= 0.95695735863181


# Gradent decent

In [67]:
ao=0
a1=0
l=0.00001
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
y = np.array([1, 3, 2, 5, 7, 8, 8, 9, 10, 12])
n=10
for i in range(1000):
      y_c= ao+(a1*x)
      ao=ao-(l*((1/n)*np.sum(y_c-y)))
      a1=a1-(l*((1/n)*np.sum((y_c-y)*x)))
      error = np.sum((y-y_c)**2)/n
      if error < 1e-6:
        break
print(ao,a1)        

0.056752011134779706 0.33730646992700997


In [73]:
import numpy as np

ao = 0
a1 = 0
l = 0.01
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
y = np.array([1, 3, 2, 5, 7, 8, 8, 9, 10, 12])
n = 10
for i in range(10000):
    y_c=ao+(a1*x)
    ao=ao-(l / n)*np.sum(y_c-y)
    a1=a1-(l/n)*np.sum((y_c-y)*x)
    error=np.sum((y-y_c)** 2)/n
    if error<1e-6:
        break
print(ao,a1)

1.2363636363630979 1.1696969696970558


In [75]:
print(ao + (a1 * x))

[ 1.23636364  2.40606061  3.57575758  4.74545455  5.91515152  7.08484848
  8.25454545  9.42424242 10.59393939 11.76363636]
